--------------------------------------------------------
--  파일이 생성됨 - 일요일-11월-12-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COUNTRY
--------------------------------------------------------

  CREATE TABLE "C##TREVEL"."COUNTRY" 
   (	"COUNTRYID" NUMBER, 
	"COUNTRYNAME" VARCHAR2(100 BYTE), 
	"STAFF" VARCHAR2(40 BYTE), 
	"PRICE" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "C##TREVEL"."CUSTOMER" 
   (	"CUSTID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCAL_FOOD
--------------------------------------------------------

  CREATE TABLE "C##TREVEL"."LOCAL_FOOD" 
   (	"FOODID" NUMBER, 
	"FOODNAME" VARCHAR2(100 BYTE), 
	"COUNTRYNAME" VARCHAR2(100 BYTE), 
	"PRICE" NUMBER(20,0), 
	"COUNTRYID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "C##TREVEL"."ORDERS" 
   (	"ORDERID" NUMBER, 
	"CUSTID" NUMBER, 
	"COUNTRYID" NUMBER, 
	"SALEPRICE" NUMBER(20,0), 
	"ORDERDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SOUVENIR
--------------------------------------------------------

  CREATE TABLE "C##TREVEL"."SOUVENIR" 
   (	"SOUVENIRID" NUMBER, 
	"SOUVENIRNAME" VARCHAR2(100 BYTE), 
	"COUNTRYNAME" VARCHAR2(100 BYTE), 
	"PRICE" NUMBER(20,0), 
	"COUNTRYID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TOURIST_SPOT
--------------------------------------------------------

  CREATE TABLE "C##TREVEL"."TOURIST_SPOT" 
   (	"SPOTID" NUMBER, 
	"SPOTNAME" VARCHAR2(100 BYTE), 
	"COUNTRYNAME" VARCHAR2(100 BYTE), 
	"PRICE" NUMBER(20,0), 
	"COUNTRYID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "C##TREVEL"."USERS" 
   (	"USERID" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"USER_ID" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"IS_ADMIN" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##TREVEL.COUNTRY
SET DEFINE OFF;
Insert into C##TREVEL.COUNTRY (COUNTRYID,COUNTRYNAME,STAFF,PRICE) values (1,'영국','손흥민',1900000);
Insert into C##TREVEL.COUNTRY (COUNTRYID,COUNTRYNAME,STAFF,PRICE) values (2,'일본','송범근',500000);
Insert into C##TREVEL.COUNTRY (COUNTRYID,COUNTRYNAME,STAFF,PRICE) values (3,'핀란드','박세리',1300000);
Insert into C##TREVEL.COUNTRY (COUNTRYID,COUNTRYNAME,STAFF,PRICE) values (4,'호주','박지성',1400000);
REM INSERTING into C##TREVEL.CUSTOMER
SET DEFINE OFF;
Insert into C##TREVEL.CUSTOMER (CUSTID,NAME,ADDRESS,PHONE) values (8,'이재성','독일 뮌헨','000-6784-1232');
Insert into C##TREVEL.CUSTOMER (CUSTID,NAME,ADDRESS,PHONE) values (1,'박찬호','영국 맨체스터','000-1234-5678');
Insert into C##TREVEL.CUSTOMER (CUSTID,NAME,ADDRESS,PHONE) values (2,'김수로','영국 런던','000-2234-5678');
Insert into C##TREVEL.CUSTOMER (CUSTID,NAME,ADDRESS,PHONE) values (3,'유재석','대한민국 서울','000-3234-5678');
Insert into C##TREVEL.CUSTOMER (CUSTID,NAME,ADDRESS,PHONE) values (4,'이용진','미국 클리블랜드','000-4234-5678');
Insert into C##TREVEL.CUSTOMER (CUSTID,NAME,ADDRESS,PHONE) values (5,'탁재훈','대한민국 대전','NULL');
Insert into C##TREVEL.CUSTOMER (CUSTID,NAME,ADDRESS,PHONE) values (6,'이강인','프랑스 파리','NULL');
Insert into C##TREVEL.CUSTOMER (CUSTID,NAME,ADDRESS,PHONE) values (7,'김민재','독일 뮌헨','000-5678-1234');
REM INSERTING into C##TREVEL.LOCAL_FOOD
SET DEFINE OFF;
Insert into C##TREVEL.LOCAL_FOOD (FOODID,FOODNAME,COUNTRYNAME,PRICE,COUNTRYID) values (5,'Nando''s','영국',30000,1);
Insert into C##TREVEL.LOCAL_FOOD (FOODID,FOODNAME,COUNTRYNAME,PRICE,COUNTRYID) values (6,'Fish Plaice','영국',25000,1);
Insert into C##TREVEL.LOCAL_FOOD (FOODID,FOODNAME,COUNTRYNAME,PRICE,COUNTRYID) values (7,'오와리야 시조텐','일본',120000,2);
Insert into C##TREVEL.LOCAL_FOOD (FOODID,FOODNAME,COUNTRYNAME,PRICE,COUNTRYID) values (8,'효테이','일본',90000,2);
Insert into C##TREVEL.LOCAL_FOOD (FOODID,FOODNAME,COUNTRYNAME,PRICE,COUNTRYID) values (9,'Forza','핀란드',20000,3);
Insert into C##TREVEL.LOCAL_FOOD (FOODID,FOODNAME,COUNTRYNAME,PRICE,COUNTRYID) values (10,'Harald','핀란드',30000,3);
Insert into C##TREVEL.LOCAL_FOOD (FOODID,FOODNAME,COUNTRYNAME,PRICE,COUNTRYID) values (11,'Pancakes On the Rocks','호주',50000,4);
Insert into C##TREVEL.LOCAL_FOOD (FOODID,FOODNAME,COUNTRYNAME,PRICE,COUNTRYID) values (12,'Bourke Street Bakery','호주',45000,4);
Insert into C##TREVEL.LOCAL_FOOD (FOODID,FOODNAME,COUNTRYNAME,PRICE,COUNTRYID) values (1,'Old Compton Brasserie','영국',20000,1);
Insert into C##TREVEL.LOCAL_FOOD (FOODID,FOODNAME,COUNTRYNAME,PRICE,COUNTRYID) values (2,'미시마테이','일본',80000,2);
Insert into C##TREVEL.LOCAL_FOOD (FOODID,FOODNAME,COUNTRYNAME,PRICE,COUNTRYID) values (3,'Ekberg','핀란드',16000,3);
Insert into C##TREVEL.LOCAL_FOOD (FOODID,FOODNAME,COUNTRYNAME,PRICE,COUNTRYID) values (4,'Grill Steak Seafood','호주',65000,4);
REM INSERTING into C##TREVEL.ORDERS
SET DEFINE OFF;
Insert into C##TREVEL.ORDERS (ORDERID,CUSTID,COUNTRYID,SALEPRICE,ORDERDATE) values (1,1,1,1900000,to_date('23/11/12','RR/MM/DD'));
Insert into C##TREVEL.ORDERS (ORDERID,CUSTID,COUNTRYID,SALEPRICE,ORDERDATE) values (2,2,1,1900000,to_date('23/11/13','RR/MM/DD'));
Insert into C##TREVEL.ORDERS (ORDERID,CUSTID,COUNTRYID,SALEPRICE,ORDERDATE) values (3,3,2,500000,to_date('23/11/14','RR/MM/DD'));
Insert into C##TREVEL.ORDERS (ORDERID,CUSTID,COUNTRYID,SALEPRICE,ORDERDATE) values (4,4,3,1300000,to_date('23/11/15','RR/MM/DD'));
REM INSERTING into C##TREVEL.SOUVENIR
SET DEFINE OFF;
Insert into C##TREVEL.SOUVENIR (SOUVENIRID,SOUVENIRNAME,COUNTRYNAME,PRICE,COUNTRYID) values (1,'캐드버리 초콜릿','영국',8900,1);
Insert into C##TREVEL.SOUVENIR (SOUVENIRID,SOUVENIRNAME,COUNTRYNAME,PRICE,COUNTRYID) values (2,'해리포터 마법지팡이','영국',128000,1);
Insert into C##TREVEL.SOUVENIR (SOUVENIRID,SOUVENIRNAME,COUNTRYNAME,PRICE,COUNTRYID) values (3,'로이스 초콜릿','일본',9000,2);
Insert into C##TREVEL.SOUVENIR (SOUVENIRID,SOUVENIRNAME,COUNTRYNAME,PRICE,COUNTRYID) values (4,'사케','일본',50000,2);
Insert into C##TREVEL.SOUVENIR (SOUVENIRID,SOUVENIRNAME,COUNTRYNAME,PRICE,COUNTRYID) values (5,'무민샵','핀란드',24000,3);
Insert into C##TREVEL.SOUVENIR (SOUVENIRID,SOUVENIRNAME,COUNTRYNAME,PRICE,COUNTRYID) values (6,'Marimekko','핀란드',30000,3);
Insert into C##TREVEL.SOUVENIR (SOUVENIRID,SOUVENIRNAME,COUNTRYNAME,PRICE,COUNTRYID) values (7,'BLACKMORES omega3','호주',23000,4);
Insert into C##TREVEL.SOUVENIR (SOUVENIRID,SOUVENIRNAME,COUNTRYNAME,PRICE,COUNTRYID) values (8,'FLATOUTbear','호주',48000,4);
REM INSERTING into C##TREVEL.TOURIST_SPOT
SET DEFINE OFF;
Insert into C##TREVEL.TOURIST_SPOT (SPOTID,SPOTNAME,COUNTRYNAME,PRICE,COUNTRYID) values (9,'버킹엄 궁전','영국',25000,1);
Insert into C##TREVEL.TOURIST_SPOT (SPOTID,SPOTNAME,COUNTRYNAME,PRICE,COUNTRYID) values (10,'타워브리지','영국',18000,1);
Insert into C##TREVEL.TOURIST_SPOT (SPOTID,SPOTNAME,COUNTRYNAME,PRICE,COUNTRYID) values (11,'닛코국립공원','일본',12000,2);
Insert into C##TREVEL.TOURIST_SPOT (SPOTID,SPOTNAME,COUNTRYNAME,PRICE,COUNTRYID) values (12,'히메지 성','일본',30000,2);
Insert into C##TREVEL.TOURIST_SPOT (SPOTID,SPOTNAME,COUNTRYNAME,PRICE,COUNTRYID) values (1,'영국박물관','영국',100000,1);
Insert into C##TREVEL.TOURIST_SPOT (SPOTID,SPOTNAME,COUNTRYNAME,PRICE,COUNTRYID) values (2,'런던 아이','영국',60000,1);
Insert into C##TREVEL.TOURIST_SPOT (SPOTID,SPOTNAME,COUNTRYNAME,PRICE,COUNTRYID) values (3,'금각사','일본',6000,2);
Insert into C##TREVEL.TOURIST_SPOT (SPOTID,SPOTNAME,COUNTRYNAME,PRICE,COUNTRYID) values (4,'기요미데즈라','일본',20000,2);
Insert into C##TREVEL.TOURIST_SPOT (SPOTID,SPOTNAME,COUNTRYNAME,PRICE,COUNTRYID) values (5,'무민월드','핀란드',35000,3);
Insert into C##TREVEL.TOURIST_SPOT (SPOTID,SPOTNAME,COUNTRYNAME,PRICE,COUNTRYID) values (6,'산타클로스 마을','핀란드',30000,3);
Insert into C##TREVEL.TOURIST_SPOT (SPOTID,SPOTNAME,COUNTRYNAME,PRICE,COUNTRYID) values (7,'오페라하우스','호주',90000,4);
Insert into C##TREVEL.TOURIST_SPOT (SPOTID,SPOTNAME,COUNTRYNAME,PRICE,COUNTRYID) values (8,'울루루','호주',16000,4);
REM INSERTING into C##TREVEL.USERS
SET DEFINE OFF;
Insert into C##TREVEL.USERS (USERID,USERNAME,USER_ID,PASSWORD,IS_ADMIN) values (1,'박효제','abc1','abc1',1);
--------------------------------------------------------
--  DDL for Index SYS_C008314
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TREVEL"."SYS_C008314" ON "C##TREVEL"."COUNTRY" ("COUNTRYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008317
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TREVEL"."SYS_C008317" ON "C##TREVEL"."CUSTOMER" ("CUSTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008316
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TREVEL"."SYS_C008316" ON "C##TREVEL"."LOCAL_FOOD" ("FOODID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008318
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TREVEL"."SYS_C008318" ON "C##TREVEL"."ORDERS" ("ORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008325
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TREVEL"."SYS_C008325" ON "C##TREVEL"."SOUVENIR" ("SOUVENIRID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008315
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TREVEL"."SYS_C008315" ON "C##TREVEL"."TOURIST_SPOT" ("SPOTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008321
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TREVEL"."SYS_C008321" ON "C##TREVEL"."USERS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008322
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TREVEL"."SYS_C008322" ON "C##TREVEL"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table COUNTRY
--------------------------------------------------------

  ALTER TABLE "C##TREVEL"."COUNTRY" ADD PRIMARY KEY ("COUNTRYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "C##TREVEL"."CUSTOMER" ADD PRIMARY KEY ("CUSTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCAL_FOOD
--------------------------------------------------------

  ALTER TABLE "C##TREVEL"."LOCAL_FOOD" ADD PRIMARY KEY ("FOODID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "C##TREVEL"."ORDERS" ADD PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SOUVENIR
--------------------------------------------------------

  ALTER TABLE "C##TREVEL"."SOUVENIR" ADD PRIMARY KEY ("SOUVENIRID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TOURIST_SPOT
--------------------------------------------------------

  ALTER TABLE "C##TREVEL"."TOURIST_SPOT" ADD PRIMARY KEY ("SPOTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "C##TREVEL"."USERS" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##TREVEL"."USERS" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCAL_FOOD
--------------------------------------------------------

  ALTER TABLE "C##TREVEL"."LOCAL_FOOD" ADD CONSTRAINT "FK_COUNTRY_LOCAL_FOOD" FOREIGN KEY ("COUNTRYID")
	  REFERENCES "C##TREVEL"."COUNTRY" ("COUNTRYID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "C##TREVEL"."ORDERS" ADD FOREIGN KEY ("CUSTID")
	  REFERENCES "C##TREVEL"."CUSTOMER" ("CUSTID") ENABLE;
  ALTER TABLE "C##TREVEL"."ORDERS" ADD FOREIGN KEY ("COUNTRYID")
	  REFERENCES "C##TREVEL"."COUNTRY" ("COUNTRYID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SOUVENIR
--------------------------------------------------------

  ALTER TABLE "C##TREVEL"."SOUVENIR" ADD FOREIGN KEY ("COUNTRYID")
	  REFERENCES "C##TREVEL"."COUNTRY" ("COUNTRYID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TOURIST_SPOT
--------------------------------------------------------

  ALTER TABLE "C##TREVEL"."TOURIST_SPOT" ADD CONSTRAINT "FK_COUNTRY" FOREIGN KEY ("COUNTRYID")
	  REFERENCES "C##TREVEL"."COUNTRY" ("COUNTRYID") ENABLE;
